source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DOOgre_Example', :exclusive => true do
  pod "DOOgre", :path => "../"
end

target 'DOOgre_Tests', :exclusive => true do
  pod "DOOgre", :path => "../"

  
end
